<?xml version="1.0"?>
<robot name="my_robot_2wd" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find my_2wd_robot)/urdf/2wd_properties.urdf.xacro" />
  <xacro:include filename="$(find my_2wd_robot)/urdf/robot_parts/base.urdf.xacro" />
  <xacro:include filename="$(find my_2wd_robot)/urdf/robot_parts/wheel.urdf.xacro" />
  <xacro:include filename="$(find my_2wd_robot)/urdf/robot_parts/caster_wheel.urdf.xacro" />
  <xacro:include filename="$(find my_2wd_robot)/urdf/controllers/diff_drive.urdf.xacro" />
  <xacro:include filename="$(find my_2wd_robot)/urdf/sensors/lidar.xacro" />
  <xacro:include filename="$(find my_2wd_robot)/urdf/sensors/camera.xacro" />

  
  <xacro:base 
    length="${base_length}" 
    width="${base_width}" 
    height="${base_height}" 
    mass="${base_mass}"
    wheel_radius="${wheel_radius}"
    wheel_pos_z="${wheel_pos_z}"
/>

  <xacro:wheel 
    side="left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:wheel 
    side="right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:if value="${front_caster_wheel}">
    <xacro:caster_wheel 
      side="front"
      mass="0.01"
      base_length="${base_length}" 
      wheel_radius="${wheel_radius}" 
      wheel_pos_z="${wheel_pos_z}" 
    />
  </xacro:if>

  <xacro:if value="${rear_caster_wheel}">
    <xacro:caster_wheel 
      side="rear"
      mass="0.01"
      base_length="${base_length}" 
      wheel_radius="${wheel_radius}" 
      wheel_pos_z="${wheel_pos_z}" 
    />
  </xacro:if>

  <xacro:diff_drive_controller
    wheel_separation="${wheel_pos_y * 2}"
    wheel_radius="${wheel_radius}"
    wheel_torque="${wheel_torque}"
  />
  
  <xacro:if value="${lidar_enabled}">
    <xacro:lidar
      radius="0.05" 
      length="0.04" 
    />
  </xacro:if>

  <xacro:if value="${camera_enabled}">
    <xacro:camera
      radius="0.03" 
      length="0.05" 
    />
  </xacro:if>


</robot>